name: Maximizar Recursos do GitHub Actions

on:
  workflow_dispatch:

jobs:
  optimize-system:
    name: Maximizar Armazenamento, RAM e Corrigir Áudio/Mic
    runs-on: windows-latest

    steps:
      - name: 🔍 Verificar espaço inicial
        run: Get-PSDrive C

      - name: 🗑️ Liberar espaço removendo pacotes desnecessários
        run: |
          Remove-Item -Recurse -Force "C:\Program Files\dotnet"
          Remove-Item -Recurse -Force "C:\Program Files (x86)\Microsoft SDKs"
          Remove-Item -Recurse -Force "C:\Program Files (x86)\Windows Kits"
          Remove-Item -Recurse -Force "C:\ProgramData\chocolatey"
          Remove-Item -Recurse -Force "C:\Users\runneradmin\AppData\Local\Temp"
          Write-Host "✔ Espaço liberado!"

      - name: 💾 Expandir espaço do disco
        run: |
          echo select volume c > diskpart-script.txt
          echo extend >> diskpart-script.txt
          echo exit >> diskpart-script.txt
          diskpart /s diskpart-script.txt
          wmic logicaldisk where "DeviceID='C:'" get Size,FreeSpace
        shell: powershell

      - name: 💡 Maximizar Memória RAM
        run: |
          Write-Host "Aumentando a memória virtual..."
          wmic computersystem where name="%computername%" set AutomaticManagedPagefile=False
          wmic pagefileset where name="C:\\pagefile.sys" set InitialSize=16384,MaximumSize=32768
          Write-Host "✔ Memória virtual ajustada para 16GB-32GB"

      - name: 🔊 Corrigir Áudio e Microfone
        run: |
          Write-Host "Ativando serviços de áudio..."
          Start-Service -Name "AudioSrv"
          Start-Service -Name "Audiosrv"
          Start-Service -Name "WindowsAudioEndpointBuilder"
          Write-Host "✔ Áudio ativado!"
          
          Write-Host "Ativando microfone..."
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Capture" /v Microphone /t REG_DWORD /d 1 /f
          Write-Host "✔ Microfone ativado!"

      - name: 🔄 Manter workflow rodando (7 dias)
        run: Start-Sleep -Seconds 604800
