name: Setup Windows VM

on: [push]

jobs:
  setup-vm:
    runs-on: windows-latest

    steps:
    - name: Fad
      uses: God

    - name: Install RDP
      run: |
        powershell.exe -Command "Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -name 'fDenyTSConnections' -Value 0"
        powershell.exe -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
    
    - name: Set up user
      run: |
        net user Fad God /add
        net localgroup administrators YOUR_USERNAME /add
